TEAMS = [
["Baltimore Ravens", "AFC North"],
["Cincinnati Bengals", "AFC North"],
["Cleveland Browns", "AFC North"],
["Pittsburgh Steelers", "AFC North"],
["Houston Texans", "AFC South"],
["Indianapolis Colts", "AFC South"],
["Jacksonville Jaguars", "AFC South"],
["Tennessee Titans", "AFC South"],
["Buffalo Bills", "AFC East"],
["Miami Dolphins", "AFC East"],
["New England Patriots", "AFC East"],
["New York Jets", "AFC East"],
["Denver Broncos", "AFC West"],
["Kansas City Chiefs", "AFC West"],
["Oakland Raiders", "AFC West"],
["San Diego Chargers", "AFC West"],
["Chicago Bears", "NFC North"],
["Detroit Lions", "NFC North"],
["Green Bay Packers", "NFC North"],
["Minnesota Vikings", "NFC North"],
["Atlanta Falcons", "NFC South"],
["Carolina Panthers", "NFC South"],
["New Orleans Saints", "NFC South"],
["Tampa Bay Buccaneers", "NFC South"],
["Dallas Cowboys", "NFC East"],
["New York Giants", "NFC East"],
["Philadelphia Eagles", "NFC East"],
["Washington Redskins", "NFC East"],
["Arizona Cardinals", "NFC West"],
["San Francisco 49ers", "NFC West"],
["Seattle Seahawks", "NFC West"],
["St. Louis Rams", "NFC West"]
]