#encoding: utf-8

MOCK_1 = [["Jadeveon Clowney","The buzz is building for Blake Bortles to land in this spot, but I'm holding to my belief that the Texans will take the best available talent and that's Clowney."],
["Greg Robinson","Robinson will immediately upgrade the Rams' rushing attack and he has all of the tools to develop into an elite pass protector."],
["Sammy Watkins","The Jaguars pass on a quarterback here and select a receiver with Pro Bowl potential."],
["Jake Matthews","Matthews has played both right and left tackle in college. He would line up at right tackle for the Browns and give them one of the top tackle tandems in the NFL."],
["Blake Bortles","The Raiders quietly filled some holes in free agency, but they still need a long-term solution at the quarterback position."],
["Khalil Mack","The Falcons need help along the offensive line, but they also have a glaring need for a dynamic edge rusher. Mack fits that description."],
["Taylor Lewan","Lewan's combination of athleticism and toughness would be a nice addition to the Buccaneers' offense."],
["Johnny Manziel","The Vikings have a strong running game that would complement Manziel's style of play."],
["Mike Evans","Evans' combination of size, speed and ball skills would fit nicely in Doug Marrone's offense."],
["Justin Gilbert","The Lions have some talented young cornerbacks on their roster. However, Gilbert is a true difference maker and he would be tough to pass up."],
["Anthony Barr","Barr's speed off the edge would be a welcome addition to Ray Horton's defense."],
["Eric Ebron","The Giants need more weapons on offense and grabbing the top tight end in the draft would be a good place to start."],
["Ha Ha Clinton-Dix","The Rams could look at the receiver position, but there will be plenty of talented pass catchers still on the board in the second and third rounds. Clinton-Dix is a ballhawking safety that would complement the physical play of T.J. McDonald."],
["Timmy Jernigan","Jernigan has both the strength to hold the point of attack and the quickness to shoot through gaps and disrupt."],
["Odell Beckham","Beckham is gaining steam as we head toward the draft. He is explosive with the ball in his hands and he's a weapon in the return game as well."],
["Aaron Donald","The Cowboys just signed Henry Melton, but that shouldn't scare them away from Donald. He is a dominant interior defender, but he has the quickness and athleticism to slide out to defensive end if needed."],
["Calvin Pryor","The Ravens took a safety in the first round last year, but they need another one after the departure of James Ihedigbo in free agency."],
["Brandin Cooks","The Jets need offensive playmakers and Cooks is an explosive weapon with outstanding production."],
["Zack Martin","Miami moved quickly to sign Branden Albert, but there is still plenty of work to be done to rebuild this offensive line."],
["Bradley Roby","Roby had a few rough outings during the 2013 season, but his 2012 tape is outstanding and he's starting to gain steam in personnel circles."],
["C.J. Mosley","Mosley would be a perfect fit in Dom Capers' defense. He is very tough, instinctive and productive."],
["Darqueze Dennard","Dennard had an average combine workout, but he's very consistent on tape."],
["Marqise Lee","Lee didn't run quite as fast as anticipated, but he's electric with the ball in his hands."],
["Kyle Fuller","The Bengals have a loaded roster, but there are a few question marks at the corner position."],
["Louis Nix","Nix was an inconsistent player on tape, but he has the size and quickness to develop into a disruptive three-down player."],
["Teddy Bridgewater","I still view Bridgewater as the top quarterback in this draft class, but he has failed to generate excitement among the personnel executives I've talked to. If he falls past the Titans at pick No. 11, I think it's realistic he could slide all the way down to this spot."],
["Dee Ford","Ford's stock took off after a dominant week at the Senior Bowl, and he built off that performance by putting together an impressive pro day. He has double-digit sack potential."],
["Kelvin Benjamin","The Panthers are in desperate need of wide receivers and Benjamin would be a lethal red-zone weapon for Cam Newton."],
["Xavier Su'a-Filo","Su'a-Filo would provide a nice upgrade to the interior of the Patriots' offensive line. He is very smart, athletic and nasty. Those are three traits shared by current Patriots guard Logan Mankins."],
["Jason Verrett","The 49ers have a stacked roster and they should be in position to simply take the best available player. Verrett can play inside or outside, and he has outstanding awareness and ball skills."],
["Ryan Shazier","Shazier ran a sub-4.40 40-yard dash at 237 pounds during Ohio State's pro day. He is an outstanding blitzer and he has the athleticism to mirror tight ends all over the field."],
["Morgan Moses","Moses has excellent size and length. He isn't a great athlete, but he stays on his feet and rarely gets beat in pass protection. He is a Day 1 starter at right tackle."]]

MOCK_2 = [["Jadeveon Clowney", "Clowney's lack of production this season is a concern, but his combination of size and explosiveness will be too tough to pass up."],
["Greg Robinson", "Robinson will immediately upgrade the Rams' rushing attack and he has all of the tools to develop into an elite pass protector."],
["Khalil Mack", "The Jaguars pass on a quarterback here and elect to nab the best available pass rusher."],
["Sammy Watkins", "The Browns hold off on a quarterback and select the top playmaker in the draft."],
["Johnny Manziel", "Manziel will undergo a lot of media scrutiny, but there are a lot of teams very excited about his pro potential."],
["Jake Matthews", "The Falcons need to get much better up front and Matthews is a polished pass protector."],
["Blake Bortles", "Mike Glennon played above expectations during his rookie campaign, but I'm not convinced he's the long-term solution at the position."],
["Teddy Bridgewater", "The Vikings need to upgrade the quarterback position and Bridgewater is capable of playing Day 1."],
["Mike Evans", "Evans put on a show in Indianapolis and his blend of size/speed would fit nicely in Doug Marrone's offense."],
["Justin Gilbert", "Gilbert's combine performance created a buzz in scouting circles and likely cemented his status as the top cover man in the draft."],
["Anthony Barr", "Barr would be a nice fit in Ray Horton's defense."],
["Taylor Lewan", "Lewan is consistent on tape and he put together an outstanding combine workout."],
["Calvin Pryor", "Pryor is a very physical run defender and he has the athleticism to range off the hash and make a play on the ball."],
["Timmy Jernigan", "The Bears have a desperate need at the safety position, but Jernigan is too good to pass up at this point in the draft."],
["C.J. Mosley", "The Steelers defense needs help up the middle and Mosley is a ready-made pro."],
["Aaron Donald", "Donald is gaining steam after a dominant season, Senior Bowl and NFL Scouting Combine."],
["Eric Ebron", "Ebron would flourish in Gary Kubiak's system."],
["Brandin Cooks", "The Jets need offensive playmakers and Cooks is an explosive weapon with outstanding college production."],
["Zack Martin", "Miami must address the offensive line during the offseason and Martin is one of the more consistent players in this draft class."],
["Bradley Roby", "Roby had a few rough outings this year, but his 2012 tape is outstanding and he had an impressive workout at the combine."],
["Ha Ha Clinton-Dix", "The Packers are in a division with elite pass catchers and they need a rangy safety to plug into their defense."],
["Darqueze Dennard", "Dennard had an average combine workout, but he's very consistent on tape."],
["Odell Beckham", "Beckham is very explosive and he's also one of the best returners in the draft."],
["Dee Ford", "The Bengals defense is loaded, but you can never have enough pass rushers."],
["Jason Verrett", "Verrett had an outstanding combine performance, and he has the ability to play both outside and in the slot."],
["Derek Carr", "Carr has a very strong arm and his intangibles are off the charts."],
["Morgan Moses", "Moses didn't test very well at the combine, but his tape is solid and he has the size/skill set to develop into an upper echelon right tackle."],
["Marqise Lee", "Lee was measured smaller and timed slower than evaluators hoped. However, his tape is too good to ignore."],
["RaShede Hageman", "Hagemen was expected to put on a show at the combine and he didn't disappoint."],
["Louis Nix", "The 49ers need to add more depth along the defensive line and Nix has the ability to develop into a three-down player."],
["Kony Ealy", "Ealy ran slower than expected but he plays much faster on tape and his versatility is very appealing."],
["Kelvin Benjamin", "Benjamin would be an outstanding red-zone target for Russell Wilson."]]

MOCK_3 = [["Jadeveon Clowney", "Blake Bortles fits the Bill O'Brien quarterback profile but passing on Clowney will prove to be difficult."],
["Greg Robinson", "Robinson will provide a physical presence in the run game and he has the tools to be a dominant pass protector."],
["Johnny Manziel", "The Jaguars could take a pass rusher or WR Sammy Watkins, but Manziel’s playmaking ability would provide a much-needed spark for their offense."],
["Teddy Bridgewater", "The Browns have been searching for a franchise quarterback for more than a decade and Bridgewater’s combination of accuracy, poise and toughness is very appealing."],
["Blake Bortles", "The Raiders could go in several different directions, but they need a long-term solution at quarterback."],
["Khalil Mack", "The Falcons’ pass rush needs to be upgraded, and Mack is the second-best edge rusher in the draft."],
["Anthony Barr", "Barr could play linebacker in the Bucs’ base defense and put his hand on the ground in passing situations."],
["C.J. Mosley", "If the top three quarterbacks are off the board, Mosley would be a great fit in Mike Zimmer’s defense."],
["Sammy Watkins", "In this scenario, the Bills couldn’t pass up the most dynamic offensive player in the draft."],
["Justin Gilbert", "The Lions have some talented young cornerbacks, but Gilbert is on another level and he would match up well with the bigger wideouts in the NFC North."],
["Jake Matthews", "Matthews would be an upgrade over veteran right tackle David Stewart and he could eventually replace Michael Roos on the left side."],
["Taylor Lewan", "The Giants could look at cornerback or wide receiver with this pick, but they have a long track record of selecting linemen in the first round."],
["Mike Evans", "Adding Robinson and Evans would give the Rams a physical offense to pair with one of the best young defenses in the NFL."],
["Timmy Jernigan", "The Bears have a desperate need at the safety position, but Jernigan is too good to pass up at this point in the draft."],
["Kelvin Benjamin", "Benjamin’s size and playmaking ability would be a perfect complement to Antonio Brown."],
["Calvin Pryor", "The Cowboys have a need at safety and Pryor’s combination of range, ball skills and toughness would be tough to pass up."],
["Eric Ebron", "Ebron would flourish in offensive coordinator Gary Kubiak’s system."],
["Marqise Lee", "The Jets need to surround Geno Smith with more firepower and Lee has been a big-play machine throughout his college career."],
["Zack Martin", "Miami must address the offensive line during the offseason and Martin is one of the more consistent players in this draft class."],
["Morgan Moses", "Moses helped himself with a rock-solid performance at the Senior Bowl and he’s capable of playing either left or right tackle."],
["Ha Ha Clinton-Dix", "The Packers are in a division with elite pass catchers and they need a rangy safety to plug into their defense."],
["Darqueze Dennard", "The Eagles need to upgrade their secondary and Dennard is a physical cornerback with outstanding ball skills."],
["Brandin Cooks", "Cooks is a very explosive vertical threat and he’s also a polished route runner."],
["RaShede Hageman", "The Hageman Express is going to leave the station after he works out in Indianapolis."],
["Louis Nix", "Nix has the tools to be a dominant three-down player in the Chargers’ defensive system."],
["Carlos Hyde", "Hyde’s combination of power, speed and vision would fit nicely alongside the Browns’ other offensive weapons."],
["Kony Ealy", "Ealy has a huge upside as an edge rusher and he would fill a position of need for Rob Ryan’s defense."],
["Davante Adams", "Cam Newton needs more weapons and Adams is a red-zone machine with double-digit touchdown potential."],
["Jace Amaro", "Amaro could put up monster numbers playing in this offense."],
["Bradley Roby", "Roby is an explosive, fluid athlete that would fit nicely in the 49ers’ secondary."],
["Jarvis Landry", "Landry won’t run a fast 40-time, but he’s a savvy route-runner with outstanding toughness and ball skills."],
["Stephon Tuitt", "The Seahawks have a very deep roster and that will allow them to take the best available player."]]

MOCK_4 = [["Jadeveon Clowney", "Bill O'Brien doesn't see much difference between the first and second tier of quarterbacks, leading him to take the best available player in the draft."],
["Jake Matthews", "Jake Long's injury prompts Fisher to add insurance to an offensive line that needs to handle the formidable frontlines in the NFC West."],
["Khalil Mack", "Gus Bradley has watched Pete Carroll build a Super Bowl champion with the quarterback playing a secondary role. He could opt to add a defensive playmaker to the mix to help the Jaguars compete against the Indianapolis Colts and Andrew Luck."],
["Sammy Watkins", "Surrounding a quarterback with explosive weapons is never a bad option. GM Ray Farmer could add Watkins to an offensive lineup up that features Pro Bowl-caliber players in WR Josh Gordon and TE Jordan Cameron."],
["Greg Robinson", "Matt Schaub lacks athleticism and mobility. Thus, Reggie McKenzie could opt to build a fortress at the line of scrimmage to help his franchise quarterback thrive in the pocket."],
["Anthony Barr", "Taylor Lewan could be in play at this selection, but the need to add an explosive 3-4 edge rusher is a bigger priority in this scenario."],
["Taylor Lewan", "Jason Licht and Lovie Smith have fortified the defense through free agency. Adding a stout offensive tackle on the right side should stabilize an offense that has tremendous potential."],
["Aaron Donald", "The re-signing of Matt Cassel gives Rick Spielman plenty of options on draft day. He could replace Kevin Williams with a Geno Atkins-clone who is an ideal fit in Mike Zimmer's aggressive scheme."],
["Eric Ebron", "Doug Marrone is 'all-in' on EJ Manuel, so adding weapons to the passing game is a priority. Texas A&M WR Mike Evans would fit the bill, but the Bills could opt for a big, athletic tight end to exploit voids in the middle of the field."],
["Timmy Jernigan", "GM Martin Mayhew issued a warning shot to Nick Fairley by refusing to pick up the option year on his rookie contract. Adding Jernigan would increase depth and competition at defensive tackle, while giving the Lions options if they need to part ways with Fairley or Ndamukong Suh down the road."],
["Justin Gilbert", "The presence of the three top quarterbacks on the board could entice Ken Whisenhunt to make a move considering Jake Locker's struggles. But adding Gilbert gives the team the lockdown corner that's needed to match up with the talented No. 1 receivers in the AFC South."],
["Mike Evans", "The loss of Hakeem Nicks elevates Rueben Randle in the rotation, but it could prompt GM Jerry Reese to make a play for a prototypical No. 1 receiver like Evans at this point."],
["Ha Ha Clinton-Dix", "Despite public sentiment favoring the addition of an explosive wide receiver, Fisher could elect to fill the biggest need on defense by taking the top free safety in the class."],
["RaShede Hageman", "Taking Hageman at this point would be considered a reach by some, but the Bears' porous defense desperately needs size and athleticism along the frontline."],
["Darqueze Dennard", "Dennard is the hard-nosed, gritty defender that the Steelers have coveted for years. He is a perfect fit in Dick LeBeau's system as a tenacious press-man corner."],
["Kony Ealy", "The departure of DeMarcus Ware forces Jerry Jones to look for a viable replacement in the draft. Although Ealy is a developmental prospect at this stage of his career, he possesses all of the athletic attributes needed to become a standout pass rusher as a pro."],
["Zack Martin", "Gary Kubiak's arrival in Baltimore will change the core traits the Ravens' personnel department looks for in offensive linemen. Martin's athleticism, balance and technical skills are ideal fits for the Ravens' new zone-based blocking scheme."],
["Marqise Lee", "Eric Decker gives the Jets offense a steady presence on the perimeter, but the passing game still lacks an explosive playmaker. Lee is a dynamic receiver with the speed and running skills to thrive in New York's version of the West Coast offense."],
["Xavier Su'a-Filo", "No one will blame new GM Dennis Hickey for expending a top pick on an offensive guard after witnessing the Dolphins' offensive line woes a season ago. Su'a-Filo is a standout blocker with the toughness and physicality to take on the big-bodied defensive tackles that dominate the AFC East."],
["Dee Ford", "Bruce Arians could always pull a fast one and select a quarterback at this point, but the need to keep up with the stellar defenses in the NFC West makes a move to add Ford a better play for the Cardinals."],
["Calvin Pryor", "Safety has been a huge weakness in the Packers defense since Nick Collins' injury. Pryor would give the Pack a thumper between the hashes to discourage opponents from taking shots down the middle."],
["Bradley Roby", "The Cary Williams signing should be viewed as a disappointment based on his inability to lock down top receivers. Roby would give the team a young, athletic cover man with the swagger to compete with elite receivers on the perimeter."],
["Odell Beckham", "Andy Reid's offensive scheme is fueled by 'catch-and-run' playmakers with the potential to turn short passes into big gains. Beckham is a spectacular offensive weapon with the potential to emerge as a force in an offense that feeds him the ball on the perimeter."],
["Ryan Shazier", "If Teddy Bridgewater is available at this point, it would be hard for Marvin Lewis to ignore the Louisville standout despite Andy Dalton's success in the Queen City. However, the thought of moving on from a quarterback with three playoff appearances under his belt in three seasons could prompt Lewis to add another playmaker to a dynamite defense."],
["Kyle Fuller", "The Chargers are intent on adding a big, athletic corner to the lineup to match up with the big-bodied receivers terrorizing the AFC. Fuller has flown under the radar for most of the process, but coaches and scouts are starting to fall in love with his athleticism, length and competitiveness on the perimeter."],
["Jason Verrett", "With the top three quarterbacks still on the board, GM Ray Farmer could elect to take another position player and take the best available quarterback at the top of the second round. Verrett would likely rank as the top cover corner in the draft if he was a few inches taller, so the addition of the TCU standout would give the Browns a formidable nickel package with Joe Haden and Buster Skrine on the perimeter."],
["C.J. Mosley", "The Saints could use another big body on the offensive or defensive line, but Mosley's versatility meshes well with Rob Ryan's defensive scheme."],
["Cyrus Kouandjio", "The recent retirmement of Jordan Gross will force the Panthers to scrap their plans of adding a pass catcher early in the draft. Kouandjio is raw and unrefined at this point, but his size, strength and length should make him a capable starter at left tackle."],
["Louis Nix", "The Patriots are notorious for trading away picks, so this could be the landing point for one of the top three quarterbacks. If not, Nix is a viable option with Vince Wilfork chirping about a possible release."],
["Brandin Cooks", "The 49ers have a pair of big-bodied pass catchers in Michael Crabtree and Anquan Boldin, but the receiving corps needs an explosive slot receiver to add diversity to the unit. Cooks is the most polished receiver in the 2014 class, with a game that fits in nicely with the 49ers' scheme."],
["Travis Swanson", "The Broncos have won the free-agency sweepstakes by all accounts, but the team still needs to tweak the offensive line. Swanson is a smart pivot with superb skills and instincts."],
["Kelvin Benjamin", "The loss of Sidney Rice and Golden Tate leaves a void in the Seahawks' receiving corps. Benjamin is a big, athletic pass catcher with the potential to wreak havoc in the red zone."]]

MOCK_5 = [["Jadeveon Clowney", "Coach Bill O'Brien could certainly opt for a quarterback at the top spot, but passing on a mercurial talent like Clowney could be hard to justify down the road."],
["Jake Matthews", "Questions about Matthews' overall athleticism could prompt the Rams to take Greg Robinson at this pick. However, coach Jeff Fisher's relationship with Bruce Matthews could sway the Rams in this direction."],
["Johnny Manziel", "Coach Gus Bradley has seen the impact of a diminutive playmaker with exceptional skills after spending a season with Russell Wilson in Seattle. With Manziel displaying similar athletic traits and a dynamic personality, Bradley could hand the keys to the Jaguars offense to the former Heisman Trophy winner."],
["Teddy Bridgewater", "Offensive coordinator Kyle Shanahan's adaptable offense makes Bridgewater a terrific fit in Cleveland. The Louisville star is a polished pocket passer, but is athletic enough to execute the movement-based passing game that's a staple of Shanahan's system."],
["Blake Bortles", "Coach Dennis Allen and GM Reggie McKenzie are under strict orders to win in 2014 or risk losing their jobs. Hitting a home run on a quarterback could earn a reprieve from the firing line."],
["Greg Robinson", "GM Thomas Dimitroff has openly discussed the need to improve in the trenches after seeing Matt Ryan get sacked 44 times. Robinson is a dominant edge player with the strength, power and athleticism to pummel defensive ends on the perimeter."],
["Anthony Barr", "Coach Lovie Smith will make getting after the passer a priority in Tampa. Barr is an explosive linebacker with blitz skills. Additionally, he has the size and athleticism to match up with the big-bodied tight ends that dominate the NFC South."],
["Khalil Mack", "Expect coach Mike Zimmer to put a huge emphasis on playing great defense in Minnesota. Mack is a disruptive defender capable of helping the Vikings produce more turnovers in 2014."],
["Eric Ebron", "The Bills offense features intriguing weapons on the perimeter, but a threat down the middle would take the passing game to another level. Ebron is an athletic playmaker with the size and speed to overwhelm defenders between the hashes."],
["Sammy Watkins", "The Lions desperately need a home-run hitter opposite Calvin Johnson to take advantage of the one-on-one matchups on the backside. Watkins is a big play waiting to happen with the ball in his hands."],
["Justin Gilbert", "The Titans could look to upgrade the secondary by adding a playmaking corner with size, speed and athleticism. Gilbert also brings value as a dangerous return man in the kicking game."],
["Taylor Lewan", "GM Jerry Reese needs to fortify the frontline after watching Eli Manning nearly beaten to pulp in the pocket. Lewan is an underrated athlete with a game that is quickly rounding into form."],
["Darqueze Dennard", "The rise of press coverage in the NFC West could lead Jeff Fisher to add a young, physical corner to the mix. Dennard is technically sound with a gritty demeanor that ideally suits new defensive coordinator Gregg Williams."],
["Timmy Jernigan", "The Florida State star is an ideal fit as a three-technique in a penetrating 4-3 scheme. Jernigan would shine in a system conducive to his skills as a disruptive defender."],
["Ha Ha Clinton-Dix", "The Steelers have to find a replacement for Ryan Clark and Troy Polamalu in the back end. Clinton-Dix is a perfect fit as a playmaking safety with outstanding ball skills and awareness."],
["Calvin Pryor", "Finding a playmaking safety in the deep middle is a top priority for the Cowboys. Pryor is a hard hitter with underrated playmaking ability."],
["Mike Evans", "The loss of Anquan Boldin robbed Joe Flacco of a big-bodied receiver to target in the red zone. Evans is a jump ball specialist with the length and athleticism to dominate smaller defenders on the perimeter."],
["Marqise Lee", "The Jets desperately need a playmaker on the perimeter to help Geno Smith take his game to the next level. Lee is super explosive with the ball in his hands."],
["Zack Martin", "The Richie Incognito-Jonathan Martin scandal leaves the Dolphins with a huge void along the frontline. Martin is a versatile player capable of excelling at guard or tackle for the 'Phins."],
["Austin Seferian-Jenkins", "The Cardinals have developed a lethal passing game under Arians, but a big-bodied pass catcher between the hashes would create more room for Larry Fitzgerald and Michael Floyd."],
["Louis Nix", "Defensive coordinator Dom Capers returns as the defensive coordinator, but the Packers need to replenish the defensive line to help the defense return to prominence. Nix is a stout run stuffer at the point of attack, with enough athleticism to provide a push against the pass."],
["Brandin Cooks", "Coach Chip Kelly's explosive offense is built around speedy playmakers on the outside. Cooks is a big play artist with the speed and quickness to excel as a vertical threat or 'catch and run' specialist."],
["Odell Beckham", "The lack of speed and quickness on the perimeter prevents the Chiefs from pushing the ball down the field in the passing game. Beckham, Jr. is a speedster with exceptional quickness and burst. Plus, he shows excellent running skills with the ball in his hands. Those traits are coveted in coach Andy Reid's version of the west coast offense."],
["Kony Ealy", "Michael Johnson is unlikely to return as a high-priced free agent, leading coach Marvin Lewis to lean toward taking the ultra-athletic Ealy to serve as his replacement."],
["Jason Verrett", "A porous secondary limited the Chargers' ability to open up the defensive playbook. Verrett could allow the team to incorporate man-to-man coverage with his natural instincts and cover skills."],
["Bradley Roby", "New general manager Ray Farmer has promised to throw some curveballs in the draft. Drafting Roby would rank as a surprise to some, but adding a top-notch corner opposite Joe Haden would ensure the Browns are capable of matching up with high-flying offenses dominating the AFC."],
["Stephon Tuitt", "The recent release of Will Smith creates another void along the Saints' frontline. Tuitt is an athletic five-technique with the size and length to occupy multiple blockers at the point of attack."],
["Cyrus Kouandjio", "The possible retirement of Jordan Gross could force the Panthers to use their first selection on a big-bodied edge blocker. Kouandjio moves defenders off the ball and exhibits enough lateral quickness to hold up in pass protection."],
["Jace Amaro", "It's critical to give Tom Brady a few more weapons on the perimeter to make a legitimate run at the Super Bowl. Amaro is a sneaky athletic tight end with strong hands and outstanding ball skills."],
["RaShede Hageman", "The 49ers would love to pair Aldon Smith with a young athletic defender with exceptional size and length. Hageman has been a bit of an underachiever at Minnesota, but his natural talent is undeniable."],
["C.J. Mosley", "John Elway will look to remake the Broncos defense with an emphasis on young, athletic playmakers. Mosley is a versatile linebacker capable of staying on the field in every situation."],
["David Yankey", "The presence of a dominant running game sets the table for Russell Wilson and company. Yankey is a powerful run blocker at the point of attack, yet also shows the at[hleticism to execute pulls and traps on the move."]]

MOCK_6 = [["Jadeveon Clowney", "A QB gets strong consideration, but Texans opt for top QB disrupter."],
["Sammy Watkins", "The most dynamic offensive playmaker in the draft pumps up the Rams' attack."],
["Khalil Mack", "Jags lean to head coach Gus Bradley's roots and build with defense."],
["Teddy Bridgewater", "Not the greatest pro day, but three seasons of excellent game tape were not erased. Still, Browns could wait until pick No. 26 to take a QB (Derek Carr?)."],
["Greg Robinson", "The OT with the most upside gets the nod over a QB, which is a huge need for the Raiders."],
["Jake Matthews", "An edge rusher would be nice. ... Keeping QB Matt Ryan healthy is vital."],
["Johnny Manziel", "Free-agency moves allow Bucs to shoot for the magic."],
["Blake Bortles", "Vikings start over for new head coach Mike Zimmer, but could still opt for defense."],
["Mike Evans", "A desired target for a young QB."],
["Justin Gilbert", "The top CB on my board, he's needed vs. passing attacks of the NFC North."],
["Anthony Barr", "One of my favorite players in the draft, Barr will be directed to disrupt Colts QB Andrew Luck."],
["Taylor Lewan", "Many needs on defense, but QB Eli Manning faced a lot of pressure in 2013."],
["Ha Ha Clinton-Dix", "With the top OTs gone, Rams get center fielder to patrol secondary."],
["Timmy Jernigan", "It might be a passing league, but people took the land route vs. Da Bears. The shoring-up process starts here."],
["Darqueze Dennard", "Steelers would be excited to see the former Spartans star still available."],
["Calvin Pryor", "Cowboys seeking to upgrade safety position. Done."],
["Eric Ebron", "Not a need pick, but too talented to pass up if he lasts this long."],
["Odell Beckham", "The building continues around QB Geno Smith, but Rex Ryan might really want a CB."],
["Zack Martin", "Dolphins hold their breath that Baltimore doesn't take the durable technician out of South Bend."],
["Bradley Roby", "All-Pro Patrick Peterson needs a complement on the corner."],
["Brandin Cooks", "WR James Jones recently signed with Oakland. The flier from Corvallis is exactly what QB Aaron Rodgers is seeking."],
["C.J. Mosley", "An all-purpose LB who provides speed and thump needed in the NFC East."],
["Kelvin Benjamin", "Kansas City needs help keeping the running lanes open for RB Jamaal Charles."],
["Dee Ford", "DE Michael Johnson departed in free agency, so a versatile pass rusher makes his way to the Midwest."],
["Marqise Lee", "Picture this smooth, big-play threat opposite WR Keenan Allen."],
["Xavier Su'a-Filo", "If they fill their QB need at pick No. 4, this is a player who will really help protect him."],
["Kyle Fuller", "The big WRs in the NFC South create a need for bigger, talented CBs."],
["Jarvis Landry", "How can this team not have a plethora of WRs surrounding QB Cam Newton?!"],
["Louis Nix", "No more Vince Wilfork means the Pats need a big presence to try to replace him. 'Irish Chocolate' is eager to try."],
["RaShede Hageman", "Motor not consistent, but 49ers' locker room and staff could bring out the best of him."],
["Jason Verrett", "People are afraid of his lack of size. They should embrace his coverage and tackling skills."],
["Aaron Donald", "The Geno Atkins comparisons are apt, and he helps the 'Hawks keep their inside pressure on QBs ramped up."]]

MOCK_7 = [["Blake Bortles", "Did everything at the combine to show that he's willing to stand up and be 'The Guy.'"],
["Jadeveon Clowney", "Another pass rusher for the Rams?! You can never have enough."],
["Johnny Manziel", "His style of play will be modified, yet nurtured and welcomed by the Jaguars' staff."],
["Teddy Bridgewater", "His pro day carries extra scrutiny now since he sat out the workout at the combine."],
["Sammy Watkins", "Seems like a perfect pick for the Raiders, doesn't he?"],
["Greg Robinson", "He wowed us at the combine. New OL coach Mike Tice's smile will be huge."],
["Khalil Mack", "Athletic, and edgy ... just what new head coach Lovie Smith wants for his defense."],
["Anthony Barr", "A versatile player for the Vikings to use as they try to disrupt Aaron Rodgers, Jay Cutler and Matthew Stafford."],
["Mike Evans", "A big-time running mate for Stevie Johnson, as promised by head coach Doug Marrone."],
["Justin Gilbert", "Gets the nod over Darqueze Dennard of Michigan State."],
["C.J. Mosley", "More than looked the part in field drills, and he looks even better on game tape."],
["Jake Matthews", "Talent that fills a need makes for a good draft pick. Eli Manning would approve."],
["Taylor Lewan", "Lots of talk about a WR here, but they can't afford to pass on O-line help. Lewan was terrific at the combine."],
["Timmy Jernigan", "Extra bulk to help the Bears' dismal run defense. Aaron Donald of Pitt would be tempting here."],
["Darqueze Dennard", "Steelers seeking help throughout their defense. Dennard brings talent and toughness."],
["Zack Martin", "He was lost in the shuffle in Indy, but Martin is a really good player who can play guard and maybe center, too."],
["Ha Ha Clinton-Dix", "Performed well at the combine. Rangy, center fielder who is better than advertised in man coverage."],
["Eric Ebron", "His explosiveness was evident at the combine. The Jets and QB Geno Smith need him."],
["Cyrus Kouandjio", "Did not test as well in Indy as desired, but he's talented and would fill a crying need for the Dolphins."],
["Dee Ford", "Flies off the edge, and can work into the rotation similar to the way Aldon Smith did in San Francisco."],
["Calvin Pryor", "A hammer in the run game, and has good range vs. the pass."],
["Bradley Roby", "A strong finish to his season coupled with an impressive combine sends him to the NFC East champs."],
["Aaron Donald", "What a season, Senior Bowl and combine for the former Pitt Panther. Now squarely in first-round discussion."],
["Kony Ealy", "Versatile, and the Bengals will never shy away from adding good defenders."],
["Louis Nix", "The Chargers continue to fortify their playoff team with the big nose tackle."],
["Carlos Hyde", "Browns need a runner to help their young QB acclimate, and Hyde eats carries."],
["RaShede Hageman", "This youngster showed his skills in Indy, and defensive coordinator Rob Ryan will bring out the best in him."],
["Tre Mason", "Put on a very nice performance at the combine."],
["Jace Amaro", "A disappointing combine, but his game tape shows he can play. His pro day will be much better, I'm sure."],
["Odell Beckham", "Dazzled in Indy, so much so that the 49ers might pass up the bigger body in Florida State WR Kelvin Benjamin."],
["Jason Verrett", "Ran 4.38 in the 40-yard dash, had a vertical jump of 39 inches and had the best footwork of the cornerbacks in Indy. I am not worried about his size."],
["Brandin Cooks", "His 4.33 40-yard dash got everyone's attention. So did his good routes, and sure hands during field drills."]]

MOCK_8 = [["Jadeveon Clowney", "If a QB is taken here, expect it to be UCF's Blake Bortles."],
["Jake Matthews", "There's uncertainty over LT Jake Long's recovery, and a need to protect QB Sam Bradford."],
["Johnny Manziel", "Head coach Gus Bradley and OC Jedd Fisch are the right personalities for Johnny Football."],
["Teddy Bridgewater", "He's still in play for the first pick with Houston. The Browns are in restart mode, again."],
["Sammy Watkins", "Fast, strong, sure hands -- he's a true playmaker."],
["Greg Robinson", "Pass rushers are needed, but the OL has to be improved to help unleash the Falcons' firepower."],
["Anthony Barr", "This former RB is now a feared defender, and he can rush the passer which is a must vs. division foes Brees, Ryan and Newton."],
["Blake Bortles", "A stunning ascent for the pride of Oviedo, Fla. He'll need to bring a big coat as the Vikes play outside for the next two seasons."],
["Khalil Mack", "It's too perfect, isn't it? The scourge of the MAC is rated higher that UCLA's Anthony Barr by many scouts."],
["Justin Gilbert", "A dual threat as a returner, he can cover and makes plenty of plays on the ball."],
["C.J. Mosley", "Titans seeking more speed and striking ability on defense."],
["Taylor Lewan", "Eli Manning needs help, and Lewan provides it along with that extra bit of nasty, as well."],
["Marqise Lee", "Injuries slowed him last season, but his ceiling is high. He would complement 2013 first-rounder Tavon Austin quite well."],
["Louis Nix", "The Bears really need help shoring up their run defense, and if Nix's medical checks out after a late-season injury, he's ideal."],
["Mike Evans", "Tall, rangy receiver who can run. He fits the Steelers' need for bigger bodies at the position."],
["Ha Ha Clinton-Dix", "The Cowboys changed defensive coordinators again. They need players to make Rod Marinelli's schemes work."],
["Zack Martin", "Exceptional Senior Bowl week helps convince the Ravens that he's the guy to help get Ray Rice untracked."],
["Eric Ebron", "What really helps a young QB? A TE who can work the seams and create easier throws. Ebron is gifted."],
["Cyrus Kouandjio", "There's no question that OT is a need for the Dolphins, and the big man from Alabama can fill it."],
["Darqueze Dennard", "Long speed is the only question mark for this former Spartan. If he runs well at the combine, look out."],
["Bradley Roby", "He was a bit inconsistent last season, but he has plenty of ability."],
["Calvin Pryor", "Big hitter, but in today's NFL, his ability to cover is what makes him a first-rounder."],
["Stephon Tuitt", "Kansas City gets a guy that can play the run and rush the passer as the Chiefs set their sights on Denver."],
["Timmy Jernigan", "Geno Atkins must return from injury, and Jernigan provides a great tag-team partner."],
["Kony Ealy", "He's not as publicized as DE teammate Michael Sam, but Ealy is a more versatile player who can rush from different spots."],
["Odell Beckham", "This pick will get heavy, heavy discussion in the Browns' draft room. A runner is a possibility, but so is help for Josh Gordon."],
["Dee Ford", "He should convert to OLB, but will serve as pass rusher in nickel and sub packages. He dominated the Senior Bowl practices and game."],
["Carlos Hyde", "The best RB in college football by the end of last season, he can assume the run-game load for the Panthers."],
["Aaron Donald", "Popular thought is a TE selection here, but when have the Pats been conventional?"],
["Kelvin Benjamin", "Back to the WR well for the Niners. Benjamin is a youngster that can be groomed."],
["Jason Verrett", "Many battles will be had in draft rooms about his size, but he's a real ballhawk that makes a ton of plays."],
["Allen Robinson", "Sidney Rice and Golden Tate could be gone, but the former Nittany Lion has exceptional ball skills ."]]

MOCK_9 = [["Teddy Bridgewater", "A very fluid pick here for the Texans. This is not set in stone."],
["Jake Matthews", "Sam Bradford is the Rams' QB. They have to protect him."],
["Johnny Manziel", "Yes, the Jags will start over at QB, too. Johnny Football could be their guy."],
["Jadeveon Clowney", "If Johnny Manziel is gone, the Browns might continue to fortify a good defense."],
["Marqise Lee", "The Raiders need players at a number of positions, and Lee is a game breaker."],
["Anthony Barr", "Barr is a terrific player who can really rush the passer."],
["Khalil Mack", "Many scouts have Mack rated higher than Anthony Barr."],
["Blake Bortles", "No player will be more scrutinized in the pre-draft process."],
["Taylor Lewan", "The Wolverines' stalwart has plenty of nasty to him."],
["Darqueze Dennard", "Home-state cornerback is a good fit for Lions."],
["Cyrus Kouandjio", "The Titans are still trying to solidify their offensive line."],
["Greg Robinson", "More protection for Eli Manning is needed."],
["Sammy Watkins", "Watkins would give the Rams more speed to try to catch San Francisco and Seattle."],
["Louis Nix", "Stopping the run is a priority for the Bears in 2014."],
["C.J. Mosley", "Tough and physical linebacker would be perfect fit in Pittsburgh."],
["Ha Ha Clinton-Dix", "The safety position has been an issue for years in Dallas."],
["Mike Evans", "A helpful target for Joe Flacco, but offensive line is a need, too."],
["Ryan Shazier", "The Jets' defensive line is very good, but they could use some playmakers on the edges."],
["Zack Martin", "Offensive line is a big need, and this LT really impressed me vs. Stanford's terrific defense."],
["Justin Gilbert", "A long CB to pair with All-Pro Patrick Peterson."],
["Stephon Tuitt", "Tuitt can play the run and rush the passer."],
["Calvin Pryor", "Pryor would give the Eagles a physical presence in the secondary."],
["Kelvin Benjamin", "The Chiefs need to establish a presence downfield, and Benjamin could provide it."],
["Bradley Roby", "Roby must clean up a few things, but he has plenty of ability."],
["Jace Amaro", "Antonio Gates can't go on forever ... can he?"],
["Derek Carr", "They'll be tempted to take a runner here, but QBs are hard to turn down."],
["Antonio Richardson", "Keeping Drew Brees upright is always a priority for New Orleans."],
["Carlos Hyde", "It's time to start over at the RB position, and Hyde is this year's Eddie Lacy (and possibly better)."],
["Austin Seferian-Jenkins", "It was a somewhat disappointing season for him, but a good pre-draft circuit puts him back on the map."],
["Timmy Jernigan", "Jernigan would give the 49ers another good player to fortify a dynamic defense."],
["Jason Verrett", "Verrett's size will give them pause, but his playmaking is exceptional."],
["Allen Robinson", "Robinson is underrated nationally, but he is a good route runner with tremendous ball skills."]]

MOCK_10 = [["Jadeveon Clowney", ""],
["Sammy Watkins", ""],
["Anthony Barr", ""],
["Johnny Manziel", ""],
["Teddy Bridgewater", ""],
["Greg Robinson", ""],
["Khalil Mack", ""],
["Blake Bortles", ""],
["C.J. Mosley", ""],
["Mike Evans", ""],
["Jake Matthews", ""],
["Justin Gilbert", ""],
["Taylor Lewan", ""],
["Timmy Jernigan", ""],
["Kelvin Benjamin", ""],
["Calvin Pryor", ""],
["Marqise Lee", ""],
["Eric Ebron", ""],
["Zack Martin", ""],
["Cyrus Kouandjio", ""],
["Ha Ha Clinton-Dix", ""],
["Darqueze Dennard", ""],
["Paul Richardson", ""],
["RaShede Hageman", ""],
["Lamarcus Joyner", ""],
["Carlos Hyde", ""],
["Kony Ealy", ""],
["Jarvis Landry", ""],
["Jace Amaro", ""],
["Louis Nix", ""],
["Morgan Moses", ""],
["Davante Adams", ""]]

MOCK_11 = [["Jadeveon Clowney", "Bill O'Brien bypasses the chance to take a quarterback to pair Clowney with J.J. Watt to create a formidable frontline."],
["Greg Robinson", "Jake Long's injury prompts Jeff Fisher to secure a franchise tackle to protect Sam Bradford."],
["Teddy Bridgewater", "General manager David Caldwell tabs Bridgewater to be the new face of the franchise."],
["Johnny Manziel", "Johnny Football would energize an organization desperate for a legitimate franchise quarterback."],
["Blake Bortles", "Bortles is not a finished product, but the Raiders could view him as an upgrade over Terrelle Pryor and Matt McGloin."],
["Anthony Barr", "Barr could give the Dirty Birds a pass-rushing presence that was absent in 2013 after the departure of John Abraham."],
["Jake Matthews", "Lovie Smith would like to find a pass rusher to solidify the defense, but Matthews would complete a physically imposing offensive line."],
["Khalil Mack", "The Vikings defense needs an infusion of youth and athleticism along the frontline. Mack fits the bill as a versatile linebacker capable of rushing the passer or dropping into coverage."],
["Eric Ebron", "General manager Doug Whaley will look to add an explosive weapon in the middle of the field to help foster the growth of E.J. Manuel."],
["Justin Gilbert", "he secondary has been the weakest link of the Lions defense for years. Gilbert will not only upgrade the back end, but he would become a star playing behind a ferocious frontline that creates persistent pressure on the passer."],
["Ha Ha Clinton-Dix", "It's time for the Titans to had a playmaker in the middle of the field. Clinton-Dix is capable of thumping runners in the hole, while also floating over the top to eliminate the deep ball."],
["Taylor Lewan", "General manager Jerry Reese and coach Tom Coughlin will look to add a skilled big body to an offensive line desperate for a franchise player on the edge."],
["Ryan Shazier", "The Rams could add an explosive defender to a dominant frontline that features a host of young, athletic disruptors."],
["Timmy Jernigan", "The lack of a dominant 3-technique rendered the Bears defense helpless against the run. Jernigan fills that void and gives the unit an energy player along the frontline."],
["Darqueze Dennard", "As a former defensive back coach, Steelers coach Mike Tomlin recognizes the need to add a standout corner to an aging secondary."],
["Kony Ealy", "Jerry Jones has been known to gamble on a player with significant upside. Ealy is as talented as they come, but his production doesn't match his athleticism at this point."],
["Sammy Watkins", "A big-bodied receiver could be in play, and it would be hard for general manager Ozzie Newsome to bypass the top receiver in the draft at this point."],
["Marqise Lee", "Several receivers enjoyed better 2013 seasons, but the memory of Lee dominating the Pac-12 for two full seasons could prompt the Jets to pull the trigger on the explosive playmaker."],
["Zack Martin", "The Dolphins' offensive line struggled well before the Jonathan Martin incident, so identifying a solid offensive tackle is a top priority. Factor in Martin's ability to play inside or outside, he could be the ideal pick in Joe Philbin's mind."],
["Austin Seferian-Jenkins", "http://www.nfl.com/news/story/0ap1000000220417/article/comparing-austin-seferianjenkins-to-rob-gronkowski-fits"],
["Louis Nix", "A safety could be in play at this pick, but a stout anchor in the middle would alleviate the pressure on the linebackers in the running game."],
["Calvin Pryor", "The Eagles' secondary hasn't been right since the departure of Brian Dawkins. Pryor is a firecracker with the skills to shine as a run or pass defender in the Eagles' scheme."],
["Odell Beckham", "Beckham's explosive running skills makes him a terrific fit in Andy Reid's version of the West Coast offense."],
["C.J. Mosley", "Marvin Lewis could look to add a three-down linebacker with versatile skills to young, athletic defense."],
["Bradley Roby", "Roby would bring much-needed athleticism and playmaking ability to a Chargers secondary that struggled in pass coverage in 2013."],
["Mike Evans", "Why not add Johnny Football's favorite target to the mix to alleviate the pressure on Josh Gordon on the perimeter? Evans would not only alter coverage, but he would give Manziel a jump-ball specialist to lean on in the red zone."],
["Jason Verrett", "Rob Ryan dramatically improved the Saints defense with his exotic blitz schemes. Verrett would encourage more man coverage with his versatility and skill."],
["Brandin Cooks", "Cam Newton would love the opportunity to throw to a Steve Smith clone on the perimeter. Cooks might be the best 'catch and run' playmaker in the draft."],
["Stephon Tuitt", "Bill Belichick could view Tuitt as a Richard Seymour clone capable of wreaking havoc in the Patriots' hybrid defensive scheme."],
["RaShede Hageman", "Hageman is the kind of athlete capable of blossoming in the 49ers' program. Far from a finished product, Hageman has the size, speed and athleticism to be a dominant player on the interior."],
["Travis Swanson", "If Peyton Manning returns for 2014, it is imperative to add a solid body on the interior to fortify the middle."],
["Kelvin Benjamin", "The Seahawks are lacking a big receiver on the outside capable of wreaking havoc in the red zone. Benjamin is a Calvin Johnson-like playmaker with the size, speed and athleticism to succeed on the NFL."]]

MOCK_12 = [["Jadeveon Clowney", "The athletic freak remains the choice for the Texans due to his disruptive potential as a pass rusher. With J.J. Watt on board to provide some veteran leadership, Clowney could quickly become the player most envisioned when watching him dominate the SEC as a youngster."],
["Jake Matthews", "Greg Robinson could be in play, but Fisher's intimate knowledge of the Matthews family could make the difference in this scenario. Matthews is a 'plug and play' prospect with the skills to be a Pro Bowler early in his career."],
["Johnny Manziel", "Manziel isn't a Russell Wilson clone, but he could intrigue Gus Bradley with his athleticism and playmaking ability."],
["Sammy Watkins", "Ray Farmer has promised some curveball moves; this would certainly qualify with Teddy Bridgewater still on the board. However, Watkins would team with Josh Gordon and Jordan Cameron to give the Browns an explosive aerial attack."],
["Greg Robinson", "Reggie McKenzie could reach for a quarterback or take a franchise-caliber offensive tackle to secure the offensive line for the next decade. Robinson is an athletic marvel with the nasty disposition needed to dominate on the edges."],
["Taylor Lewan", "Protecting Matt Ryan is Thomas Dimitroff's top priority after watching the Falcons surrender 44 sacks a season ago."],
["Anthony Barr", "The argument could be waged that Buffalo LB Khalil Mack is a more polished product at this point, but Barr's length and athleticism make him a better fit as a SAM linebacker in Lovie Smith's defense."],
["Teddy Bridgewater", "The presence of Norv Turner at offensive coordinator leads the Vikings to take the most polished pocket passer in the draft. Bridgewater's experience in a pro-style, vertical passing game could help the Vikings hit the ground running in Mike Zimmer's first season."],
["Eric Ebron", "The Bills desperately need a playmaker in the middle of the field to foster EJ Manuel's development. Ebron is the most athletic tight end in the draft, with the size and athleticism to make life easier for the Bills' franchise quarterback."],
["Justin Gilbert", "The Lions need a lockdown corner to stabilize a secondary that has struggled in recent years. Gilbert is a ball-hawking corner with size, speed and athleticism to match up with the big-bodied receivers dominating the NFC North."],
["Khalil Mack", "The Titans would be delighted to see Mack fall out of the top 10. The Buffalo standout would give new defensive coordinator Ray Horton a versatile playmaker to feature in his 3-4 scheme."],
["Mike Evans", "Adding Evans to the mix would give Eli Manning a big-bodied receiver to target in the red zone. With vivid memories of Plaxico Burress terrorizing NFC East opponents in his hey day, Jerry Reese could make a wild-card selection to help his quarterback get back on track."],
["Darqueze Dennard", "Conventional wisdom would suggest that the Rams need a No. 1 receiver, but Fisher's defensive background could lead him to take the top press corner in the draft to keep up with the elite defenses in the NFC West."],
["Timmy Jernigan", "The Bears desperately need to rebuild their defense along the frontline. Jernigan is a high-motor defender with outstanding strength and athleticism."],
["Ha Ha Clinton-Dix", "With Ryan Clark unlikely to return, the Steelers need to add a pure free safety to the lineup. Clinton-Dix is an instinctive playmaker with the speed and athleticism to eliminate the deep balls between the numbers."],
["Aaron Donald", "Rod Marinelli will energize the Cowboys' defense with his forceful personality, but he needs a disruptive three-technique in place to make the Tampa 2 scheme work. Donald is a beast at the point of attack, with a non-stop motor and explosive first-step quickness."],
["Zack Martin", "Gary Kubiak's arrival as offensive coordinator will force the Ravens to tweak their blocking schemes to feature more zone-based concepts. Martin is a terrific position blocker capable of making contributions at offensive tackle or guard."],
["Marqise Lee", "Geno Smith will never reach his potential until the Jets surround him with a talented supporting cast on the outside. Lee is a dynamic receiver with all of the tools to develop into an explosive No. 1 receiver as a pro."],
["Louis Nix", "The Dolphins elected not to place the franchise tag on NT Paul Soliai, leaving a huge void in the middle of the defense. Nix is a disruptive force at the point of attack."],
["Blake Bortles", "It would likely take a wild scenario for Bortles to be available at this stage of the draft, but the Cardinals need a young quarterback in place to succeed Carson Palmer in a year or so. Bortles is not only the right fit for Bruce Arians' system, but he undoubtedly would benefit from a year on the sidelines before being thrust into action."],
["Calvin Pryor", "The Packers' safeties were awful against the run and pass a season ago. Pryor addresses an obvious need, while giving the Packers a presence in the middle of the field that's been missing since Nick Collins roamed between the hashes."],
["Bradley Roby", "Roby is arguably the most gifted corner in the 2014 class. He is a natural No. 1 corner with the skills to match up with elite receivers."],
["Odell Beckham", "The Chiefs need more speed and explosiveness on the perimeter. Beckham is a speed merchant with a polished overall game."],
["Dee Ford", "The potential loss of Michael Johnson could put the Bengals in the market for a pass rusher. Ford is an explosive edge player with the non-stop motor and burst to become a disruptive force off the corner."],
["Jason Verrett", "Verrett might be the most complete corner in the draft. He is at his best locking down receivers in man coverage, but his willingness to thump runners on the edge makes him a likely starter from Day 1."],
["Carlos Hyde", "The Browns could certainly opt to take a quarterback at this point, but the presence of Brian Hoyer and a possible fascination with a small-school trigger man (Jimmy Garoppolo) could lead to another surprising pick. Hyde would give the Browns a rugged runner to lean on, while also allowing Ray Farmer to build up a supporting cast that's capable of carrying a young quarterback through his inevitable struggles."],
["Kony Ealy", "Rob Ryan needs more pass rushers in the stable to wreak havoc on opponents with his blitz-happy schemes. Ealy is raw, but his combination of speed and athleticism could make him a force as an edge player in an attack scheme."],
["Morgan Moses", "The retirement of Jordan Gross makes it imperative for the Panthers to solidify their offensive line. Cyrus Kouandjio could be a fit, but Moses is a superior athlete and better equipped to deal with elite pass rushers off the edge."],
["RaShede Hageman", "Bill Belichick would love to add beef to his defensive line. Hagemen is a big, athletic defender with the ability to play anywhere along the frontline."],
["Brandin Cooks", "Michael Crabtree and Anquan Boldin are a solid starting duo, but the 49ers need to add a speed receiver to the mix to open up the field for Colin Kaepernick. Cooks is a burner with tools to be an exceptional playmaker from the slot."],
["C.J. Mosley", "John Fox would like to field a faster, more athletic defense in 2014. Mosley is an instinctive defender with the speed and quickness to roam as a sideline-to-sideline playmaker."],
["Xavier Su'a-Filo", "The Seahawks played musical chairs at left guard for most of the season. Su'a-Filo shores up the biggest need on the frontline, while adding some athleticism and nastiness to the unit."]]